Database confi
Eljuan25/Enbuss pull request #1
Opened 2024-04-17 21:58 UTC by Eljuan25

configure the database from sql to postgresql so that it can be used in that way and in a more efficient way.

2024-04-18 21:32 UTC, mtopete1996 requested changes
Looks good but I'm gonna need you to squash the commits into 1 and edit the message to "Add PostgreSQL configuration and pg gem"

2024-04-18 21:53 UTC, jesusMava commented on config/database.yml
> +  username: mind
No estoy seguro si esto vaya a ocasionar problema para los demas usuarios, usualmente no se pone esta parte

2024-04-18 21:53 UTC, jesusMava commented on config/database.yml
> +  extension: postgis
Pregunta, no necesitas usar la gema 'activerecord-postgis-adapter' para habilitar postgis

2024-04-18 22:48 UTC, Eljuan25 commented on config/database.yml
> +  extension: postgis
maybe

2024-04-19 00:15 UTC, mtopete1996 approved these changes
Looks Good To Me :)

2024-04-19 19:35 UTC, jesusMava approved these changes

2024-04-19 21:15 UTC, merged