The city_stops model was created
Eljuan25/Enbuss pull request #15
Opened 2024-05-03 21:19 UTC by RichMicke

The city_stops model was created, it still needs to be finished and added values

2024-05-03 22:07 UTC, mtopete1996 approved these changes
You have an extra file 🤔

2024-05-03 22:07 UTC, mtopete1996 commented on lib/trajectories/route_22.json
> +{
This what?? Esto qué?

2024-05-03 23:28 UTC, jesusMava commented on test/fixtures/city_stops.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
are we going to use fixtures?

2024-05-03 23:40 UTC, jesusMava approved these changes

2024-05-07 22:44 UTC, mtopete1996 requested changes
You still have files that don't belong here

2024-05-07 22:59 UTC, mtopete1996 approved these changes

2024-05-07 22:59 UTC, merged