Stop migration
Eljuan25/Enbuss pull request #3
Opened 2024-04-19 23:05 UTC by RichMicke

__The fields were added to the table, the gem was added to be able to use the postgis geometry value

2024-04-24 14:59 UTC, mtopete1996 requested changes
sólo 1 cambio

2024-04-24 14:59 UTC, mtopete1996 commented on config/database.yml
> +  username: mind
Puedes borrar también este username

2024-04-24 18:08 UTC, jesusMava requested changes

2024-04-24 18:08 UTC, jesusMava commented on config/database.yml
>    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
why this config? by default rails use 5 threads, so it's not necessary the attribute `pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>`

2024-04-24 18:08 UTC, jesusMava commented on db/schema.rb
> -  create_table "spatial_ref_sys", primary_key: "srid", id: :integer, default: nil, force: :cascade do |t|
why did you delete this table?  🤔

2024-04-26 21:37 UTC, mtopete1996 approved these changes
Looks Good To Me 👍🏼

2024-04-26 22:35 UTC, jesusMava approved these changes

2024-04-26 22:50 UTC, jesusMava approved these changes

2024-04-26 22:50 UTC, jesusMava commented on db/migrate/20240426002247_units_migration.rb
> +      t.string :name
you should validate the name and capacity to avoid nils

2024-04-26 22:50 UTC, jesusMava commented on db/migrate/20240419210053_create_stops.rb
> +      t.string :name
same here

2024-04-30 22:06 UTC, mtopete1996 commented on Gemfile
> +
Remove this line, this is duplicated on this file below

2024-04-30 22:07 UTC, mtopete1996 requested changes
1 More comment

2024-04-30 22:16 UTC, mtopete1996 approved these changes
LGTM

2024-04-30 22:17 UTC, merged