create table_types
Eljuan25/Enbuss pull request #4
Opened 2024-04-23 23:57 UTC by REYNALopez12

here I just created the types table, the fields of that table were added and saved

2024-04-24 18:15 UTC, jesusMava requested changes

2024-04-24 18:15 UTC, jesusMava commented on db/schema.rb
> +    t.string "name"
I think you should validate name and description, so that they don't accept null and a minimum length for both of them.

2024-04-26 00:37 UTC, mtopete1996 approved these changes

2024-04-26 00:39 UTC, jesusMava approved these changes

2024-04-26 00:40 UTC, merged